
spring.datasource.url=jdbc:postgresql://ep-red-moon-ahdguqpc-pooler.c-3.us-east-1.aws.neon.tech:5432/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_cl4WBKntQ0oC


spring.sql.init.platform=postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Puerto en el que correra tu API Spring Boot

server.port=PORT:8080    