# ----- Configuraci�n de la conexi�n a PostgreSQL -----
spring.datasource.url=jdbc:postgresql://localhost:5432/nuevaera
spring.datasource.username=postgres
spring.datasource.password=ClavePostgres
spring.datasource.driver-class-name=org.postgresql.Driver

# Evitar que JPA intente crear/actualizar tablas autom�ticamente.
# Si tus tablas ya existen, usa 'none'. En desarrollo, podr�as usar 'update'.
spring.jpa.hibernate.ddl-auto=none

# Mostrar en consola las consultas SQL que ejecuta Hibernate (opcional)
spring.jpa.show-sql=true

# Dialecto de Hibernate para PostgreSQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Puerto en el que correr� tu API Spring Boot
server.port=8080

